Update README.md
buildo/pledge pull request #20
Opened 2017-02-05 12:58 UTC by lucacioria

2017-02-05 21:14 UTC, gabro commented on README.md
> +- close this repo, then `npm run build`, `npm run start`
Typo: cloNe

2017-02-05 21:14 UTC, gabro commented on README.md
> +- close this repo, then `npm run build`, `npm run start`
Also, I think we should "distribute" this a docker image

2017-02-06 08:58 UTC, gabro approved these changes

2017-02-07 00:31 UTC, gabro requested changes

2017-02-07 00:31 UTC, gabro commented on README.md
> +- with your browser, go to `http://my.pledge.deploy.com/add-to-slack` and authorize pledge on your slack team
I stumbled upon the URL for a few seconds wondering what magical service `http://deploy.com/` was.

Can you change this to `http://pledge.example.com/add-to-slack`?

2017-02-07 13:30 UTC, lucacioria commented
should be ok now, can I merge?

2017-02-07 18:06 UTC, merged